

training set
```{r}
rm(list = ls())
library(readr)
library(plyr)
library(readxl)
library(stringr)
library(magrittr)
source("D:/datamining_library_ge20200306.R")
df <- ge.readtable("../../../1_matrix_preprocess/covid_wz_merge20200509_filename.txt")
prot <- read_xlsx("FL02_gene_name405_20200605-1253.xlsx",sheet = 3)
prot$Gene <- gsub("-","_",prot$Gene)
prot$Gene <- gsub(";","",prot$Gene)
prot$Gene <- gsub("\\/","",prot$Gene)
prot$Gene <- gsub("@","",prot$Gene)
df1 <- df[prot$CVDTSA,]


info <- read_xlsx("../../../2_difference_analysis/batch_info20200417_1854.xlsx",sheet = 2)

names(df1) <- info$sampleid[match(names(df1),info$filename)] %>%as.character()

df1 <- df1[,!is.na(names(df1))]
names(df1) <- gsub("B",".1",names(df1))
df1 <- df1[,!grepl("p0_0",names(df1))]
df1 <- df1[,!grepl("\\.1",names(df1))]

df2 <- df1[apply(df1,1, function(x){sum(is.na(x))/ncol(df1)})<=0.8,]
df2[,1:ncol(df2)] <- as.numeric(as.matrix(df2))

label <- info$gourp[match(ge.split(names(df2),"\\.",1),info$sampleid)]
time <- as.character(ge.split(names(df2),"_",2))
time <- str_sub(time,1,1)

```

validation
```{r}
va1 <- read_xlsx("CVDSBA_Protein-20200605-1253.xlsx",sheet = 3)
va2 <- read_xlsx("CVDSBA_Protein-20200605-1253.xlsx",sheet = 4)
va_set <- merge(va1,va2,by.y = c("Proteins"))
va_set2 <- va_set[,-1]
row.names(va_set2) <- prot$CVDTSA[match( va_set$Proteins,prot$CVDSBA_swissprot)]
va_set2[va_set2=="NA"] <- NA
va_set2[,1:ncol(va_set2)] <- as.numeric(as.matrix(va_set2))
va_set3 <- va_set2[apply(va_set2,1, function(x){sum(is.na(x))/ncol(va_set2)})<=0.8,]

va.info <- read_xlsx("CVDSBA_Patient-20200605-1226.xlsx",sheet = 5)
ov <- intersect(row.names(va_set3),row.names(df2))

df3 <- df2[ov,]
row.names(df3) <- paste0(row.names(df3),"_",prot$Gene[match(row.names(df3),prot$CVDTSA)])
va_set4 <- va_set3[ov,va.info$sample]
row.names(va_set4) <- paste0(row.names(va_set4),"_",prot$Gene[match(row.names(va_set4),prot$CVDTSA)])
va.label <- va.info$type[match(names(va_set4),va.info$sample)]

```





ROC RF importance select add time 72：30  
```{r}

type123 <- which(time %in% c(1,2,3))
train_set <- data.frame(t(df3[,type123]),stringsAsFactors = F)
train_set[is.na(train_set)] <- 0
train_set$label <- label[type123]
write.csv(train_set,"train_set_matrix.csv")
####################################################
accu <- c()
for (i in seq(0,3,0.5)) {
  set.seed(2020.3)
  tmpRF2 <- randomForest(as.factor(label) ~ . ,data=train_set,importance=T,ntree=1000,nodesize=5)
  result <- data.frame(importance(tmpRF2,type=1))
  result1 <- row.names(result)[result$MeanDecreaseAccuracy>i]
  set.seed(2020.3)
 for (seed in runif(100,1,1000)) {
  for (fd in 3:6) {
  set.seed(seed)
  folds <- createFolds(train_set$label,fd)
  n=0
  	for(fold in folds){
  	  n=n+1
  	   #fold=folds[[8]]
  	   valids <- train_set[fold,result1]
  	   valids$label <- train_set$label[fold]
  	   trains <- train_set[setdiff(1:dim(train_set)[1],fold),result1]
  	   trains$label <- train_set$label[setdiff(1:dim(train_set)[1],fold)]
  	   trains$label <- as.factor(trains$label)
  	   for (ntree in seq(600,1000,200)) {
   	   set.seed(2020.3)
  	   tmpRF <- randomForest(as.factor(label) ~ . ,data=trains,importance=T,ntree=ntree,nodesize=5)
  	    fea <- data.frame(importance(tmpRF,type=1))
          for (dec in 0:3) {
            feature <- row.names(fea)[fea$MeanDecreaseAccuracy>dec]
            if(length(feature)>1){
              train2 <- trains[,feature]
              train2$label <- trains$label
              tmpRF3 <- randomForest(as.factor(label) ~ . ,data=train2,importance=T,ntree=ntree,nodesize=5)
    	  predicted <- predict(tmpRF3,valids,type='prob')
        predicts <- t(apply(predicted,1,function(v){v/sum(v)}))
        colnames(predicts) <- colnames(predicted)
        predicts <- data.frame(predicts,check.names=F)
        predicts$predicted <- apply(predicts,1,function(v){names(v)[max(v)==v]})
        predicts$observed <- valids$label
        ROC <- roc(predicts$observed, as.numeric(predicts$SC))
        auc <- as.numeric(ROC[["auc"]])
    	   acc <- sum(predicts$predicted==predicts$observed)
    	   accu <- rbind(accu,c(i,seed,fd,n,ntree,dec,acc/length(fold),auc))
  	     }
          }
  	   }
  	}
    }
  }
}
#write.csv(accu,paste0("test_174_twice_allresultv1.csv"))
# write.csv(result1,"test_feature47.csv")
tmp3 <- accu[which(accu[,7]==1 & accu[,8]==1),]


# 
# tmp3 <- read.csv("test_274_allresultv1.csv")
# tmp3 <- tmp3[,-1]
# tmp3 <- tmp3[tmp3[,6]==1 & tmp3[,7]==1,]
accu3 <- c()
for (j in 1:nrow(tmp3)) {
    set.seed(2020.3)
  tmpRF2 <- randomForest(as.factor(label) ~ . ,data=train_set,importance=T,ntree=1000,nodesize=5)
  result <- data.frame(importance(tmpRF2,type=1))
  result1 <- row.names(result)[result$MeanDecreaseAccuracy>tmp3[j,1]]


  set.seed(tmp3[j,2])
  folds <- createFolds(train_set$label,tmp3[j,3])
  	   fold=folds[[tmp3[j,4]]]
  	   valids <- train_set[fold,result1]
  	   valids$label <- train_set$label[fold]
  	   trains <- train_set[setdiff(1:dim(train_set)[1],fold),result1]
  	   trains$label <- train_set$label[setdiff(1:dim(train_set)[1],fold)]
  	   trains$label <- as.factor(trains$label)
     	   set.seed(2020.3)
    	   tmpRF <- randomForest(as.factor(label) ~ . ,data=trains,importance=T,ntree=tmp3[j,5],nodesize=5)
    	 fea <- data.frame(importance(tmpRF,type=1))
  feature <- row.names(fea)[fea$MeanDecreaseAccuracy>tmp3[j,6]]
  train2 <- trains[,feature]
  train2$label <- trains$label
  tmpRF3 <- randomForest(as.factor(label) ~ . ,data=train2,importance=T,ntree=tmp3[j,5],nodesize=5)
  	     for (time in 1:100) {
  	       sm <- sample(1:80,50)
  	       valids2 <- train_set[sm,]
  	       valids2_label <- train_set$label[sm]
  	       
    	    predicted <- predict(tmpRF3,valids2,type='prob')
          predicts <- t(apply(predicted,1,function(v){v/sum(v)}))
          colnames(predicts) <- colnames(predicted)
          predicts <- data.frame(predicts,check.names=F)
          predicts$predicted <- apply(predicts,1,function(v){names(v)[max(v)==v]})
          predicts$observed <- valids2_label
      	   acc <- sum(predicts$predicted==predicts$observed)
      	   accu3 <- rbind(accu3,c(tmp3[j,1],tmp3[j,2],tmp3[j,3],tmp3[j,4],tmp3[j,5],tmp3[j,6],acc/length(sm)))
  	     }
    	  
}
# write.csv(accu3,paste0("test_174_twice_allresultv2.csv"))
# 
# accu3 <- read.csv("test_174_twice_allresultv2.csv")
# accu3 <- accu3[,-1]
mean <- aggregate(accu3,by=list(accu3[,1],accu3[,2],accu3[,3],accu3[,4],accu3[,5]),mean)
sd <- aggregate(accu3,by=list(accu3[,1],accu3[,2],accu3[,3],accu3[,4],accu3[,5]),sd)

best <- mean[which(mean$V7==1 & sd$V7==0),]

va_set5 <-  data.frame(t(va_set4),stringsAsFactors = F)
va_set5[is.na(va_set5)] <- 0
sum <- c()
for (nn in 1:nrow(best)) {
   set.seed(2020.3)
  tmpRF2 <- randomForest(as.factor(label) ~ . ,data=train_set,importance=T,ntree=1000,nodesize=5)
  result <- data.frame(importance(tmpRF2,type=1))
  result1 <- row.names(result)[result$MeanDecreaseAccuracy>best[nn,1]]
  
  set.seed(best[nn,2])
  folds <- createFolds(train_set$label,best[nn,3])
  	   fold=folds[[best[nn,4]]]
  	   valids <- train_set[fold,result1]
  	   valids$label <- train_set$label[fold]
  	   trains <- train_set[setdiff(1:dim(train_set)[1],fold),result1]
  	   trains$label <- train_set$label[setdiff(1:dim(train_set)[1],fold)]
  	   trains$label <- as.factor(trains$label)
     	   set.seed(2020.3)
    	   tmpRF <- randomForest(as.factor(label) ~ . ,data=trains,importance=T,ntree=best[nn,5],nodesize=5)
    	 	 fea <- data.frame(importance(tmpRF,type=1))
  feature <- row.names(fea)[fea$MeanDecreaseAccuracy>best[nn,6]]
  train2 <- trains[,feature]
  train2$label <- trains$label
  tmpRF3 <- randomForest(as.factor(label) ~ . ,data=train2,importance=T,ntree=best[nn,5],nodesize=5)
  	     
    	  predicted <- predict(tmpRF3, va_set5,type='prob')
        predicts <- t(apply(predicted,1,function(v){v/sum(v)}))
        colnames(predicts) <- colnames(predicted)
        predicts <- data.frame(predicts,check.names=F)
        predicts$predicted <- apply(predicts,1,function(v){names(v)[max(v)==v]})
        predicts$observed <- va.label
    	  acc <- sum(predicts$predicted==predicts$observed)
    	  sum <- c(sum,acc)
}


###################################################


nn=309
   set.seed(2020.3)
  tmpRF2 <- randomForest(as.factor(label) ~ . ,data=train_set,importance=T,ntree=1000,nodesize=5)
  result <- data.frame(importance(tmpRF2,type=1))
  result1 <- row.names(result)[result$MeanDecreaseAccuracy>best[nn,1]]
   pdf("RF_important_select_step1.pdf")
    varImpPlot(tmpRF2,n.var=min(length(result1), nrow(tmpRF2$importance)),cex = 0.8)
   dev.off()

  set.seed(best[nn,2])
  folds <- createFolds(train_set$label,best[nn,3])
  	   fold=folds[[best[nn,4]]]
  	   valids <- train_set[fold,result1]
  	   valids$label <- train_set$label[fold]
  	   trains <- train_set[setdiff(1:dim(train_set)[1],fold),result1]
  	   trains$label <- train_set$label[setdiff(1:dim(train_set)[1],fold)]
  	   trains$label <- as.factor(trains$label)
     	   set.seed(2020.3)
    	   tmpRF <- randomForest(as.factor(label) ~ . ,data=trains,importance=T,ntree=best[nn,5],nodesize=5)
    	 	 fea <- data.frame(importance(tmpRF,type=1))
  feature <- row.names(fea)[fea$MeanDecreaseAccuracy>best[nn,6]]
  
     pdf("RF_important_select_step2.pdf")
    varImpPlot(tmpRF,n.var=min(length(feature), nrow(tmpRF$importance)),cex = 0.8)
   dev.off()
   # write.csv(row.names(valids),"valids.csv")
   # write.csv(row.names(trains),"trains..csv")
  #   fea$prot <- row.names(fea)
  # 	bar <- fea[fea$MeanDecreaseAccuracy>best[nn,6],]
  # 	bar <- bar[order(bar$MeanDecreaseAccuracy),]
  # 	n1 <- ge.split(bar$prot,"_",1)
  # 	n2 <- ge.split(bar$prot,"_",2)
  # 	bar$prot <- paste0(n1," (",n2,")")
  # 	title="feature"
  # 	
  # 	a <- ggplot(bar,aes(x=prot,y=MeanDecreaseAccuracy))+ 
  #   geom_bar(position = "dodge",stat = "identity",width =0.9,alpha=0.8)+
  #   ggtitle(paste0(title,"_barplot"))+
  #   xlab("Feature")+
  #   ylab("MeanDecreaseAccuracy")+
  # 	coord_flip()+
  #   theme(legend.text = element_text(size = 15,color = "black"),legend.position = 'top',
  #         legend.title = element_text(size=15,color="black") ,
  #         panel.grid.major =element_blank(),
  #         panel.grid.minor = element_blank(),
  #         panel.background = element_blank(),
  #         axis.line = element_line(colour = "black"))+
  # 	  scale_x_discrete(limits= as.character(bar$prot) )  +
  #   theme(panel.grid =element_blank())+
  #   theme(axis.text = element_text(size = 10,color = "black"))+
  #   theme(axis.text.x = element_text( hjust = 1))+
  #   theme(plot.subtitle=element_text(size=30, hjust=0, color="black"))+
  #   theme(axis.title.x=element_text(size=17, hjust=0.5, color="black"))+
  #   theme(axis.title.y=element_text(size=17, hjust=0.5, color="black")) 
  # ggsave(paste0(title,"_barplot.pdf"),plot=a,width=5,height=8)
  # 
  
  train2 <- trains[,feature]
  train2$label <- trains$label
  tmpRF3 <- randomForest(as.factor(label) ~ . ,data=train2,importance=T,ntree=best[nn,5],nodesize=5)

  	     
  	       
    	  predicted <- predict(tmpRF3,va_set5,type='prob')
        predicts <- t(apply(predicted,1,function(v){v/sum(v)}))
        colnames(predicts) <- colnames(predicted)
        predicts <- data.frame(predicts,check.names=F)
        predicts$predicted <- apply(predicts,1,function(v){names(v)[max(v)==v]})
        predicts$observed <- va.label
    	  acc <- sum(predicts$predicted==predicts$observed)
    	  write.csv(feature,"feature35.csv")
    	  write.csv(predicts,"SBA_set_predict20200608v4.csv")
ROC <- roc(predicts$observed,predicts$SC)
ROC[["auc"]]
pdf("ROC_20200608.pdf")
  	   plot.roc(ROC,print.auc=T,col = "blue3",ylim=c(0,1), print.thres="best",	
  main="RF test sample39 ROC",legacy.axes = TRUE,print.auc.cex=1.2)
dev.off()  	   

v <- va_set5[,feature]
ge.plot.pca(t(v),va.label,"TSA")
ge.plot.tsne(t(v),va.label,"TSA")
v2 <- train_set[,feature]
v2[is.na(v2)] <- 0
ge.plot.pca(t(v2),train_set$label, "SBA")
ge.plot.tsne(t(v2),train_set$label,"SBA")

v[,1:16] <- as.numeric(as.matrix(v))
df6 <- test_set[row.names(predicts),feature]
df7 <- apply(df6, 1, function(x){scale(as.numeric(x))})
mean <- apply( df7,2,median)
data <- data.frame(mean,predicts=predicts$SC,sample2=row.names(predicts),type2=predicts$observed )
data$type2 <- gsub("SC","1SC",data$type2)
data$type2 <- gsub("LC","2LC",data$type2)
ge.plot.point <- function(data,sample,value,type,group,title="",xlab="sample",ylab="value"){
  a <- ggplot(data,aes(x=sample,y=value,group=group,color=group))+ 
    geom_point()+geom_vline(xintercept = 0.5 ,linetype="dotted")+
    ggtitle(paste0(title,"_pointplot"))+
    xlab(xlab)+
    ylab(ylab)+
    xlim(0,1)+
    theme(legend.text = element_text(size = 15,color = "black"),legend.position = 'top',
          legend.title = element_text(size=15,color="black") ,
          panel.grid.major =element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.line = element_line(colour = "black"))+
    scale_color_manual(values=c("#FDB462","#BC80BD"))+
    theme(panel.grid =element_blank())+
    theme(axis.text = element_text(size = 10,color = "black"))+
    theme(axis.text.x = element_text( hjust = 0.5))+
    theme(plot.subtitle=element_text(size=30, hjust=0, color="black"))+
    theme(axis.title.x=element_text(size=17, hjust=0.5, color="black"))+
    theme(axis.title.y=element_text(size=17, hjust=0.5, color="black"))+  geom_text(aes(label=type,vjust = -0.5, hjust = 0.3),size = 2,show.legend = FALSE)
  ggsave(paste0(title,"_pointplot.pdf"),plot=a,width=4,height=6)
}


ge.plot.point(data,data$predicts,data$mean,data$sample2,data$type2, "RF predict2","predict value","median")
```


```{r}
combine <- rbind(train_set[,-ncol(train_set)],va_set5)
combine2 <- data.frame(t(combine),stringsAsFactors = F)
protfe <- read.csv("feature35.csv",stringsAsFactors = F)
protfe1 <- protfe$x[c(9,10,12)]
group <- 1:119
group[1:80] <- "train"  
group[81:119] <- "test"
nm.prot <- which(row.names(combine2) %in% protfe1)
label <- c(train_set$label,va.label)
for (i in nm.prot) {
  title <- row.names(combine2)[i]
  data <- data.frame(value=as.numeric(combine2[i,]),label=label,group=group )
  data$group <- paste0(data$group ,"_",data$label)
  data2 <- data
  data2$value[is.na(data2$value)] <- 0
  p.train <-  t.test(data2$value[which(as.character(ge.split(data2$group,"_",1))=="train" & data2$label=="LC")],data2$value[which(as.character(ge.split(data2$group,"_",1))=="train" & data2$label=="SC")], paired = F, var.equal = F)$p.value
    p.test <-  t.test(data2$value[which(as.character(ge.split(data2$group,"_",1))=="test" & data2$label=="LC")],data2$value[which(as.character(ge.split(data2$group,"_",1))=="test" & data2$label=="SC")], paired = F, var.equal = F)$p.value
  
  a <- ggplot(data=data, aes(x =group, y =value,group =group,fill =group,color =group)) +
    geom_jitter(alpha = 0.5,size=3 ) +
    geom_boxplot(alpha = .5,size=1,outlier.shape = NA)+
    #ylim(0,4)+
    labs(x="Group",y="Protein expression ratio",subtitle = paste0("p.train:",p.train,"\n p.test:",p.test) ,fill= "type")+
    ggtitle(paste0(title))+
    scale_x_discrete(limits= c("train_SC","train_LC","test_SC","test_LC") )+
    scale_fill_manual(values=c("#BC80BD","#FDB462","#BC80BD","#FDB462"))+
    scale_color_manual(values=c("#BC80BD","#FDB462","#BC80BD","#FDB462"))+
    theme_bw() + 
    theme(legend.position='none')+
    theme(panel.border = element_blank())+
    theme(axis.line = element_line(size=1, colour = "black")) +
    theme(panel.grid =element_blank())+  
    theme(axis.text = element_text(size = 17,colour = "black"),text = element_text(size = 15,colour = "black"))+
    theme(axis.text.x = element_text( hjust = 0.5))+
      theme(axis.title.x=element_text(size=17, hjust=0.5, color="black"))+
    theme(axis.title.y=element_text(size=17, hjust=0.5, color="black"))


  ggsave(paste0("boxplot3/",title, ".pdf"),plot=a,width=4,height=4)

}


```

```{r}
train_set2 <- df3[,type123]
train_set2 <- train_set2[feature,]
va_set6 <- va_set4[feature,]
cor_matr = cor(train_set2,va_set6,use = "pairwise.complete.obs")
 
ann_col <- data.frame(type1=va.label,
                      row.names = names(va_set6))

ann_col$type1 <- factor(ann_col$type1,levels =c("SC","LC"))
type1_color <- c("#FDB462","#BC80BD")
names(type1_color) <- c("SC","LC")


ann_row <- data.frame(type2=train_set$label,
                      row.names = names(train_set2))

ann_row$type2 <- factor(ann_row$type2,levels =c("SC","LC"))
type2_color <- c("#FDB462","#BC80BD")
names(type2_color) <- c("SC","LC")
ann_colors <- list(type1=type1_color,type2=type2_color)

df12 <- cor_matr[order(ann_row$type2),order(ann_col$type1)]
a <- pheatmap(df12, color = colorRampPalette(c("blue", "white", "red"))(20), fontsize_col = 8,
         annotation_col = ann_col,
         annotation_row = ann_row,
         annotation_colors = ann_colors,#scale = "row",
         cluster_rows = F, cluster_cols = F,show_rownames = T, show_colnames = T, 
         filename = "corheatmap_uncluster.pdf",width=9,height=9)


```



```{r}
train_set2 <- df3[,type123]
va_set6 <- va_set4[row.names(train_set2),]

mix <- cbind(train_set2,va_set6)
mix2 <- apply(mix, 2, scale)
row.names(mix2) <- row.names(mix)
cor_matr = cor(mix2,use = "pairwise.complete.obs")

mix.label <- c(train_set$label,va.label)
ann_col <- data.frame(type1=mix.label,
                      row.names = colnames(mix2))

ann_col$type1 <- factor(ann_col$type1,levels =c("SC","LC"))
type1_color <- c("#FDB462","#BC80BD")
names(type1_color) <- c("SC","LC")


ann_row <- data.frame(type2=mix.label,
                      row.names = colnames(mix2))

ann_row$type2 <- factor(ann_row$type2,levels =c("SC","LC"))
type2_color <- c("#FDB462","#BC80BD")
names(type2_color) <- c("SC","LC")
ann_colors <- list(type1=type1_color,type2=type2_color)

df12 <- cor_matr[order(ann_row$type2),order(ann_col$type1)]
a <- pheatmap(df12, color = colorRampPalette(c("blue", "white", "red"))(20), fontsize_col = 8,
         annotation_col = ann_col,
         annotation_row = ann_row,
         annotation_colors = ann_colors,#scale = "row",
         cluster_rows = F, cluster_cols = F,show_rownames = T, show_colnames = T, 
         filename = "corheatmap_uncluster20200609.pdf",width=9,height=9)


```












